services:
  inventory:
    build: .
    container_name: open_net_inventory
    # host network нужен для прямого доступа nmap к интерфейсам сервера
    network_mode: "host"
    privileged: true
    restart: always
    volumes:
      - ./inventory.db:/app/inventory.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"